CREATE TABLE good_cards (
                                id serial PRIMARY KEY,
                                content TEXT NOT NULL,
);

CREATE TABLE bad_cards (
                                id serial PRIMARY KEY,
                                content TEXT NOT NULL,
);

CREATE TABLE other_cards (
                                id serial PRIMARY KEY,
                                content TEXT NOT NULL,
);

INSERT INTO good_cards (content) VALUES
                                     ('We were into _____ before it was cool.'),
                                     ('_____ was so good even Grumpy Cat smiled.'),
                                     ('The Colonel’s secret spice contains _____.'),
                                     ('I love the smell of _____ in the morning.'),
                                     ('_____ is my chosen weapon in the zombie apocalypse.'),
                                     ('The secret weapon in the war against bad sprints is _____.'),
                                     ('_____ was all the things, to all the people.'),
                                     ('I’ll tell you what I want, what I really really want: _____.'),
                                     ('The secret to a good sprint they don’t want you to know about is _____.'),
                                     ('More beautiful than a double rainbow; when _____ just works.'),
                                     ('I want to shout it from the rooftops. I love _____.'),
                                     ('The best part of the sprint was definitely _____.'),
                                     ('If only we could bottle the magic of _____.'),
                                     ('The secret ingredient to our success is _____.'),
                                     ('I’d trade my last donut for more _____.'),
                                     ('The real MVP of this sprint was _____.'),
                                     ('When in doubt, add more _____.'),
                                     ('The best retros are fueled by _____.'),
                                     ('Our team’s spirit animal is definitely _____.'),
                                     ('The secret to a happy team is a steady supply of _____.');
                                     ('My sprint was going great until _____ showed up.'),
                                     ('If only we had more _____, everything would be perfect.'),
                                     ('This retro brought to you by the letter _____.'),
                                     ('Nothing says “teamwork” like _____.'),
                                     ('The only thing standing between us and greatness is _____.'),
                                     ('Agile works best when you add a little _____.'),
                                     ('Retros feel empty without _____.'),
                                     ('The Jira gods demand a sacrifice of _____.'),
                                     ('When life gives you bugs, make _____.'),
                                     ('During standup, someone actually said _____.'),
                                     ('All hail our new team mascot: _____.'),
                                     ('We sprint not for glory, but for _____.'),
                                     ('My post-sprint ritual includes a cup of tea and _____.'),
                                     ('The biggest surprise of the demo? _____.'),
                                     ('I opened the backlog and found _____.'),
                                     ('Our team bonding exercise turned into _____.'),
                                     ('If retros had a soundtrack, it would feature _____.'),
                                     ('The PM’s secret weapon is actually _____.'),
                                     ('My idea of a perfect Friday retro includes _____.'),
                                     ('The final form of our CI/CD pipeline is just _____.');


INSERT INTO bad_cards (content) VALUES
                                    ('_____ is the modern-day Betamax.'),
                                    ('Ain’t nobody got time for _____.'),
                                    ('The tenth circle of hell is made up of _____.'),
                                    ('_____ keeps me up at night.'),
                                    ('_____ is more offensive than the teeth of a Jeremy Kyle guest.'),
                                    ('I wouldn’t wish _____ on my worst enemy.'),
                                    ('Don’t feed gizmo after midnight or you may end up with _____.'),
                                    ('_____ should be sent to bed without supper.'),
                                    ('Drawing a perfect circle on an etch a sketch is easier than _____.'),
                                    ('The only thing I regret is _____.'),
                                    ('If only we’d known about _____ sooner.'),
                                    ('The real reason we can’t have nice things is _____.'),
                                    ('_____ is the reason I can’t have nice things.'),
                                    ('I’d rather fight a bear than deal with _____.'),
                                    ('The worst thing about retros is _____.'),
                                    ('_____ is the dark side of Agile.'),
                                    ('The only thing worse than a bad sprint is _____.'),
                                    ('_____ is the reason I need more coffee.'),
                                    ('The real reason we’re always behind schedule: _____.'),
                                    ('If only we could blame everything on _____.'),
                                    ('The secret to a bad sprint? Just add _____.'),
                                    ('I thought it was a bug, but it was actually _____.'),
                                    ('The worst part of the demo was definitely _____.'),
                                    ('I’d rather debug _____ than deal with this.');
                                    ('Nothing ruins a demo faster than _____.'),
                                    ('Every sprint ends with tears and _____.'),
                                    ('My therapist says I should talk more about _____.'),
                                    ('The real reason Jenkins is always red: _____.'),
                                    ('Our team motto? “Move fast and break _____.”'),
                                    ('The worst thing to find in a pull request: _____.'),
                                    ('Retro turned weird after someone brought up _____.'),
                                    ('Productivity was sacrificed at the altar of _____.'),
                                    ('Standup was cancelled due to a surprise outbreak of _____.'),
                                    ('QA nightmares usually involve _____.'),
                                    ('The forbidden merge button actually triggers _____.'),
                                    ('There’s a Jira ticket buried deep, labeled just _____.'),
                                    ('That wasn’t a sprint — it was _____.'),
                                    ('We deployed to production and summoned _____.'),
                                    ('Our burndown chart looks like _____.'),
                                    ('The new team member introduced themselves using _____.'),
                                    ('I thought it was a feature, but it was actually _____.'),
                                    ('The team broke Slack with too many gifs of _____.'),
                                    ('The backlog is full of _____.'),
                                    ('I’m not saying it was cursed, but it had the energy of _____.');

INSERT INTO other_cards (content) VALUES
                                      ('_____ could save the world. Or it could kill us all.'),
                                      ('I like to try new things, but is ______ really the answer?'),
                                      ('_____ didn’t go exactly how I’d have liked. But it worked.'),
                                      ('Box UK don’t currently _____, but if they did, they’d be the best in the world.'),
                                      ('______: what’s the worst that could happen?'),
                                      ('I’m 100% sure, except for maybe ______.'),
                                      ('_____ surprised me more than Chris Evans leaving Top Gear.'),
                                      ('Why didn’t we think of _____ sooner?'),
                                      ('I figured it all out, but _____ still baffles me.'),
                                      ('______ confused us more than Opal Fruits changing to Starburst.'),
                                      ('Who could have guessed that _____ would be a thing this sprint?'),
                                      ('_____ is the new black.'),
                                      ('I thought I knew everything, but then I learned about _____.'),
                                      ('The secret to success? It’s all about _____.'),
                                      ('I’m not saying it was aliens, but _____ definitely had an alien vibe.'),
                                      ('The best part of the sprint was when we discovered _____.'),
                                      ('I can’t believe we survived this sprint without _____.'),
                                      ('The real reason we’re agile? It’s all about _____.'),
                                      ('If only we had more time for _____.'),
                                      ('The best retros are fueled by _____.'),
                                      ('_____ turned out to be our team’s secret sauce.'),
                                      ('The true MVP of the sprint? _____.'),
                                      ('I didn’t believe in miracles until _____.'),
                                      ('Every team deserves a little _____.'),
                                      ('We survived this sprint thanks to _____.'),
                                      ('I nominate _____ for the unofficial team trophy.'),
                                      ('When all else fails, trust _____.'),
                                      ('Sprint magic happened right after _____.'),
                                      ('I thought _____ would break things — but it made them better.'),
                                      ('Shoutout to _____ for keeping us sane.'),
                                      ('The best part of the retro was hearing about _____.'),
                                      ('We didn’t plan for _____, but it saved the day.'),
                                      ('It all started with a cup of coffee and _____.'),
                                      ('_____ made me believe in agile again.'),
                                      ('My productivity peaked when we introduced _____.'),
                                      ('Can we talk about how awesome _____ was this sprint?'),
                                      ('In a world full of bugs, be _____.'),
                                      ('No one expected it, but _____ brought the magic.'),
                                      ('The biggest “wow” moment? Definitely _____.'),
                                      ('There’s agile, and then there’s _____.');