CREATE TABLE cards (
                       id SERIAL PRIMARY KEY,
                       content TEXT NOT NULL,
                       type VARCHAR(255) NOT NULL CHECK (type IN ('GOOD', 'BAD', 'OTHER'))
);

CREATE TABLE session_card (
                              id BIGSERIAL PRIMARY KEY,
                              session_id INTEGER NOT NULL REFERENCES active_session(id) ON DELETE CASCADE,
                              card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
                              UNIQUE (session_id, card_id)
);

INSERT INTO cards (content, type) VALUES
                                      ('We were into _____ before it was cool.', 'GOOD'),
                                      ('_____ was so good even Grumpy Cat smiled.', 'GOOD'),
                                      ('The Colonel’s secret spice contains _____.', 'GOOD'),
                                      ('I love the smell of _____ in the morning.', 'GOOD'),
                                      ('_____ is my chosen weapon in the zombie apocalypse.', 'GOOD'),
                                      ('The secret weapon in the war against bad sprints is _____.', 'GOOD'),
                                      ('_____ was all the things, to all the people.', 'GOOD'),
                                      ('I’ll tell you what I want, what I really really want: _____.', 'GOOD'),
                                      ('The secret to a good sprint they don’t want you to know about is _____.', 'GOOD'),
                                      ('More beautiful than a double rainbow; when _____ just works.', 'GOOD'),
                                      ('I want to shout it from the rooftops. I love _____.', 'GOOD'),
                                      ('The best part of the sprint was definitely _____.', 'GOOD'),
                                      ('If only we could bottle the magic of _____.', 'GOOD'),
                                      ('The secret ingredient to our success is _____.', 'GOOD'),
                                      ('I’d trade my last donut for more _____.', 'GOOD'),
                                      ('The real MVP of this sprint was _____.', 'GOOD'),
                                      ('When in doubt, add more _____.', 'GOOD'),
                                      ('The best retros are fueled by _____.', 'GOOD'),
                                      ('Our team’s spirit animal is definitely _____.', 'GOOD'),
                                      ('The secret to a happy team is a steady supply of _____.', 'GOOD'),
                                      ('My sprint was going great until _____ showed up.', 'GOOD'),
                                      ('If only we had more _____, everything would be perfect.', 'GOOD'),
                                      ('This retro brought to you by the letter _____.', 'GOOD'),
                                      ('Nothing says “teamwork” like _____.', 'GOOD'),
                                      ('The only thing standing between us and greatness is _____.', 'GOOD'),
                                      ('Agile works best when you add a little _____.', 'GOOD'),
                                      ('Retros feel empty without _____.', 'GOOD'),
                                      ('The Jira gods demand a sacrifice of _____.', 'GOOD'),
                                      ('When life gives you bugs, make _____.', 'GOOD'),
                                      ('During standup, someone actually said _____.', 'GOOD'),
                                      ('All hail our new team mascot: _____.', 'GOOD'),
                                      ('We sprint not for glory, but for _____.', 'GOOD'),
                                      ('My post-sprint ritual includes a cup of tea and _____.', 'GOOD'),
                                      ('The biggest surprise of the demo? _____.', 'GOOD'),
                                      ('I opened the backlog and found _____.', 'GOOD'),
                                      ('Our team bonding exercise turned into _____.', 'GOOD'),
                                      ('If retros had a soundtrack, it would feature _____.', 'GOOD'),
                                      ('The PM’s secret weapon is actually _____.', 'GOOD'),
                                      ('My idea of a perfect Friday retro includes _____.', 'GOOD'),
                                      ('The final form of our CI/CD pipeline is just _____.', 'GOOD');



INSERT INTO cards (content, type) VALUES
                                      ('_____ is the modern-day Betamax.', 'BAD'),
                                      ('Ain’t nobody got time for _____.', 'BAD'),
                                      ('The tenth circle of hell is made up of _____.', 'BAD'),
                                      ('_____ keeps me up at night.', 'BAD'),
                                      ('_____ is more offensive than the teeth of a Jeremy Kyle guest.', 'BAD'),
                                      ('I wouldn’t wish _____ on my worst enemy.', 'BAD'),
                                      ('Don’t feed gizmo after midnight or you may end up with _____.', 'BAD'),
                                      ('_____ should be sent to bed without supper.', 'BAD'),
                                      ('Drawing a perfect circle on an etch a sketch is easier than _____.', 'BAD'),
                                      ('The only thing I regret is _____.', 'BAD'),
                                      ('If only we’d known about _____ sooner.', 'BAD'),
                                      ('The real reason we can’t have nice things is _____.', 'BAD'),
                                      ('_____ is the reason I can’t have nice things.', 'BAD'),
                                      ('I’d rather fight a bear than deal with _____.', 'BAD'),
                                      ('The worst thing about retros is _____.', 'BAD'),
                                      ('_____ is the dark side of Agile.', 'BAD'),
                                      ('The only thing worse than a bad sprint is _____.', 'BAD'),
                                      ('_____ is the reason I need more coffee.', 'BAD'),
                                      ('The real reason we’re always behind schedule: _____.', 'BAD'),
                                      ('If only we could blame everything on _____.', 'BAD'),
                                      ('The secret to a bad sprint? Just add _____.', 'BAD'),
                                      ('I thought it was a bug, but it was actually _____.', 'BAD'),
                                      ('The worst part of the demo was definitely _____.', 'BAD'),
                                      ('I’d rather debug _____ than deal with this.', 'BAD'),
                                      ('Nothing ruins a demo faster than _____.', 'BAD'),
                                      ('Every sprint ends with tears and _____.', 'BAD'),
                                      ('My therapist says I should talk more about _____.', 'BAD'),
                                      ('The real reason Jenkins is always red: _____.', 'BAD'),
                                      ('Our team motto? “Move fast and break _____.”', 'BAD'),
                                      ('The worst thing to find in a pull request: _____.', 'BAD'),
                                      ('Retro turned weird after someone brought up _____.', 'BAD'),
                                      ('Productivity was sacrificed at the altar of _____.', 'BAD'),
                                      ('Standup was cancelled due to a surprise outbreak of _____.', 'BAD'),
                                      ('QA nightmares usually involve _____.', 'BAD'),
                                      ('The forbidden merge button actually triggers _____.', 'BAD'),
                                      ('There’s a Jira ticket buried deep, labeled just _____.', 'BAD'),
                                      ('That wasn’t a sprint — it was _____.', 'BAD'),
                                      ('We deployed to production and summoned _____.', 'BAD'),
                                      ('Our burndown chart looks like _____.', 'BAD'),
                                      ('The new team member introduced themselves using _____.', 'BAD'),
                                      ('I thought it was a feature, but it was actually _____.', 'BAD'),
                                      ('The team broke Slack with too many gifs of _____.', 'BAD'),
                                      ('The backlog is full of _____.', 'BAD'),
                                      ('I’m not saying it was cursed, but it had the energy of _____.', 'BAD');


INSERT INTO cards (content, type) VALUES
                                      ('_____ could save the world. Or it could kill us all.', 'OTHER'),
                                      ('I like to try new things, but is ______ really the answer?', 'OTHER'),
                                      ('_____ didn’t go exactly how I’d have liked. But it worked.', 'OTHER'),
                                      ('Box UK don’t currently _____, but if they did, they’d be the best in the world.', 'OTHER'),
                                      ('______: what’s the worst that could happen?', 'OTHER'),
                                      ('I’m 100% sure, except for maybe ______.', 'OTHER'),
                                      ('_____ surprised me more than Chris Evans leaving Top Gear.', 'OTHER'),
                                      ('Why didn’t we think of _____ sooner?', 'OTHER'),
                                      ('I figured it all out, but _____ still baffles me.', 'OTHER'),
                                      ('______ confused us more than Opal Fruits changing to Starburst.', 'OTHER'),
                                      ('Who could have guessed that _____ would be a thing this sprint?', 'OTHER'),
                                      ('_____ is the new black.', 'OTHER'),
                                      ('I thought I knew everything, but then I learned about _____.', 'OTHER'),
                                      ('The secret to success? It’s all about _____.', 'OTHER'),
                                      ('I’m not saying it was aliens, but _____ definitely had an alien vibe.', 'OTHER'),
                                      ('The best part of the sprint was when we discovered _____.', 'OTHER'),
                                      ('I can’t believe we survived this sprint without _____.', 'OTHER'),
                                      ('The real reason we’re agile? It’s all about _____.', 'OTHER'),
                                      ('If only we had more time for _____.', 'OTHER'),
                                      ('The best retros are fueled by _____.', 'OTHER'),
                                      ('_____ turned out to be our team’s secret sauce.', 'OTHER'),
                                      ('The true MVP of the sprint? _____.', 'OTHER'),
                                      ('I didn’t believe in miracles until _____.', 'OTHER'),
                                      ('Every team deserves a little _____.', 'OTHER'),
                                      ('We survived this sprint thanks to _____.', 'OTHER'),
                                      ('I nominate _____ for the unofficial team trophy.', 'OTHER'),
                                      ('When all else fails, trust _____.', 'OTHER'),
                                      ('Sprint magic happened right after _____.', 'OTHER'),
                                      ('I thought _____ would break things — but it made them better.', 'OTHER'),
                                      ('Shoutout to _____ for keeping us sane.', 'OTHER'),
                                      ('The best part of the retro was hearing about _____.', 'OTHER'),
                                      ('We didn’t plan for _____, but it saved the day.', 'OTHER'),
                                      ('It all started with a cup of coffee and _____.', 'OTHER'),
                                      ('_____ made me believe in agile again.', 'OTHER'),
                                      ('My productivity peaked when we introduced _____.', 'OTHER'),
                                      ('Can we talk about how awesome _____ was this sprint?', 'OTHER'),
                                      ('In a world full of bugs, be _____.', 'OTHER'),
                                      ('No one expected it, but _____ brought the magic.', 'OTHER'),
                                      ('The biggest “wow” moment? Definitely _____.', 'OTHER'),
                                      ('There’s agile, and then there’s _____.', 'OTHER');
