#name: springboot CI/CD
#
#on:
#  push:
#    branches:
#      - main
#
#env:
#  AWS_REGION: eu-west-2
#  EB_APPLICATION_NAME: retro-game-backend
#  EB_ENVIRONMENT_NAME: retro-game-backend-env
#  ARTIFACT_NAME: retro-against-humanity-backend
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    outputs:
#      version: ${{ steps.extract_version.outputs.version }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Extract version from POM
#        id: extract_version
#        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
#
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: retro-backend-package
#          path: target/${{ env.ARTIFACT_NAME }}-${{ steps.extract_version.outputs.version }}.jar
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.AWS_REGION }}
#
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: retro-backend-package
#
#      - name: Deploy
#        uses: einaregilsson/beanstalk-deploy@v22
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: ${{ env.EB_APPLICATION_NAME }}
#          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
#          version_label: ${{ github.sha}}
#          region: ${{ env.AWS_REGION }}
#          existing_bucket_name: 'elasticbeanstalk-eu-west-2-930964825207'
#          deployment_package: ${{ env.ARTIFACT_NAME }}-${{ needs.build.outputs.version }}.jar